version: '3.3'

services:
  postgres:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=GMT
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./docker/postgres/data:/postgresqldata
    networks:
      - app-network
    healthcheck:
      test: "pg_isready -p ${POSTGRES_PORT}"
  
  flyway_postgres:
    image: boxfuse/flyway:5.2.4
    command: "migrate"
    environment:
      - FLYWAY_DRIVER=${FLYWAY_DRIVER}
      - FLYWAY_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgres/migrations/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=${MONGODB_DATA_DIR}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ${MONGODB_DATA_DIR}:/mongodata/db
    command: [--auth]
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - app-network
    healthcheck:
      test: echo mongo mongo:${MONGODB_PORT}/test --quiet 1

networks: 
  app-network:
    driver: bridge

