version: '3'

services:
  flyway_postgres:
    image: boxfuse/flyway:5.2.4
    command: "migrate"
    volumes:
      - ./docker/postgres/migrations/config:/flyway/conf
      - ./docker/postgres/migrations/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - app-network
      
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=supero_challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data 
    networks:
      - app-network
    healthcheck:
      test: "pg_isready -p 5432"

    mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: supero_challenge
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supero
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/db:/data/db
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge

