CREATE TABLE account(
   id serial PRIMARY KEY,
   name VARCHAR (50) NOT NULL,
   email VARCHAR (355) UNIQUE NOT NULL,
   password VARCHAR (255) NOT NULL,
   salt VARCHAR (50) NOT NULL,
   created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);